name: CI - Tests BookFlix

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses:shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Show PHP version
        run: php -v

      - name: Run CLI tests
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          php tests/api_test_cli.php
